# Majority of the terms and meanings are based from A Simplified Computer Science Glossary
# http://marvin.cs.uidaho.edu/Teaching/CS112/terms.pdf

# Dictionaries in everyday context is a list of words with their corresponding meanings.
# Dictionaries in computing is a data structure for grouping objects. It has a set of "keys" and each "key" has an associated "value".

# In this case, we are using the data structure dictionary as the dictionary that gives meaning to words :)
# The "keys" are the words and their corresponding "value" is the meaning of the word.

dictionary = {
    "ascii": " Stands for the American Standard Code for Information Interchange. It is a 7bit code for characters. For example: the letter ’x’ is represented as 1111000. Because it is only 7 bits long, an ASCII character can be stored in a byte.",
    "abstraction": "removing detail of something to focus on a subset of the features without confusing details",
    "address": "(a) location in memory or identifying a particular piece of memory (b) an identification that allows access to something such as an internet address which allows one to access a device on the internet.",
    "agent-based modeling": "a method of simulating the real world in which individual agents interact with their environment and each other to simulate real world behaviors and conditions",
    "algorithm": "a set of instructions for accomplishing a task",
    "analog": "measured in continuous values. For example, analog computers store data in a continuous form of physical quantities (e.g. electrical, mechanical, or hydraulic phenomena) and perform calculations with the help of measures.",
    "application": "a runnable program that provides some service",
    "argument": "one of the pieces of data provided as input to a procedure or function through the call to the procedure or function",
    "artificial intelligence": "subfield of computer science that involves the creation of programs that attempt to do what was formerly believed to only be able to be done by humans",
    "assignment": "stores a value in a variable. An assignment statement has an assignment in it describing the storage of values in variables.",
    "autonomous": "controlled by computer programs and not people",
    "bandwidth": "refers to the volume of information that can be transmitted or processed. It is usually measured in bits or bytes per time unit like “bits per second”.",
    "big data": "processing vast amounts of data coming at or refreshing at very high speed. For example satellite sensor data, city monitoring sensors, gene sequencing data, etc.",
    "binary": "the base 2 number system. Integer can be encoded as binary which is a string of 0’s and 1’s. Binary is a place-value system in which each bit position denotes a power of 2 (unlike decimal which uses 10 symbols and powers of 10).",
    "bit": "a binary digit. The smallest unit of information represented by one of two states (usually 0 or 1). It is often denoted by a lower case ’b’ as in Mbs (mega-bits per second).",
    "block": "a collection of statements that can be grouped together to be treated as one statement",
    "boolean": "a data type in many programming languages that can hold either a True or a False. The name comes from the mathematician George Boole.",
    "boot program ": "the program run when the computer hardware is powered up",
    "boot": "to restart a computer as if the computer had been powered down regardless of whether it was on and running or not",
    "broadcast": "to send the same message to multiple recipients",
    "bus": "(a) the main path for bits traveling in parallel in and out of a CPU or between major computational, storage, and device components (b) any pathway for bits to travel in parallel",
    "byte": "8 bits. It is often denoted by a capital B as in MB (mega-bytes).",
    "call": "a statement in a language that starts or invokes a procedure or function",
    "central processing unit": "the computer part where the instructions are executed. It usually refers to the general purpose processor that handles a range of processing tasks.",
    "cpu intensive": "a program that spends most of its time running on the CPU",
    "cache": "memory used to speed memory access, that stores data that is anticipated to be used next or was just used and may be used again.",
    "card": "a circuit board which can be plugged into your computer motherboard",
    "character": "a single letter or symbol that is represented by a small set of bytes in the computer",
    "chip": "short for microchip, the incredibly complex yet tiny modules that store computer memory or provide logic circuitry for microprocessors",
    "clock": "the internal “drummer” or heartbeat that keeps the CPU activities across the chip and across the motherboard in sync. Often measured in megahertz or gigahertz.",
    "cloud computing": "rather than computation occurring “locally” on one’s own computer, the computation is on distant machines accessible via the internet",
    "cloud storage": "allows you to save data and files in an off-site location that you access either through the public internet or a dedicated private network connection",
    "cluster computer": "also known as a cluster is a supercomputer made up of many smaller computers such as PCs connected with very fast network hardware",
    "comment": "nonexecuting code that explains to a reader of the code in plain text what is going on",
    "comparison": "an operation that compares things. For example, if the values in two variables are equal.",
    "compile time": "the time duration in which the programming code is converted to the machine code (i.e binary code) and usually occurs before runtime",
    "compiler": "a program for translating a program written in one language into code that can be executed",
    "computer science": "(a) the study of process, data and computation (b) A very cool profession (No bias here. ;-) )",
    "computer": "an electronic device for storing and processing information based on programs stored in the computer",
    "conditional": "a control structure such as an if-statement or case-statement that conditionally executes a block of code",
    "control structure": "code or statement that changes the order of execution. For instance an if-statement conditionally executes code while a loop may perform a section of code repeatedly",
    "core": "a sub-processor on a chip. It is usually used when there are more than one processor on a single chip. Modern CPU chips often have several cores.",
    "customer base": "the set of loyal customers a company or other software supplier supports",
    "data abstraction": "giving a name to a complex set of data that forms a single concept thereby removing the need to always refer to all the detail",
    "data mining": "the process of finding anomalies, patterns and correlations within large data sets to predict outcomes",
    "data intensive": "a program that spends most of its time waiting for data from memory rather than computing",
    "database": "an organized collection of data and services to access them in a variety of ways relevant to the data",
    "declaration": "statement in a program that attaches a property to a symbol",
    "device": "a unit or piece of hardware with a specific purpose such as a disk, keyboard, audio board, etc",
    "digital divide": "the societal advantages for those with internet or computer access over those who do not have access or have limited access",
    "digital": "measured in a set of discrete steps",
    "disk": "a magnetic storage device that records data on a spinning disk",
    "drone": "a flying vehicle which may be remote-controlled or autonomous",
    "encryption": "to use a code to render data unintelligible",
    "executable": "a file that can be executed by the operating system",
    "expression": "a language construct that can be used to produce a value. For example sqrt(3) or 4+7*88",
    "file extension": "a string of characters attached to a filename, usually preceded by a full stop and indicating the format of the file",
    "file": "a single block of information allocated by an operating system for retention beyond the execution time of any program",
    "file system": "a process that manages how and where data on a storage disk, typically a hard disk drive (HDD), is stored, accessed and managed",
    "flag": "term used in reference to a Boolean variable used to answer an true or false question",
    "floating point number": "a number with a decimal in it like 3.141592653589",
    "functional abstraction": "abstraction to what a section of code will do rather that the details of how it does it. A function definition allows for abstracting the contained code to a simple call to a function",
    "function": "a standalone segment of code with a clear set of inputs and output that performs a specific function and returns a value. It is essentially a procedure that returns a value.",
    "global variable": "a variable that is accessible from anywhere in the code. It is also persistent for the duration of the program",
    "graphics processing unit": "a CPU that processes instructions specifically targeted at graphics processing",
    "graphics card": "a circuit board containing a CPU that processes instructions specifically targeted at graphics processing. This is especially useful for games and simulation programming.",
    "graphics processing": "image construction and manipulation",
    "hypertext markup language": "a language used to write internet based documents that can refer to each other",
    "hardware": "physical components of a computer or related equipment",
    "hertz": "a cycle or oscillation per second. A second hand on a standard analog clock ticks at 1 hertz. The clock on most computers is currently on the order of 1 gigahertz.",
    "hexadecimal": "a base 16 system used to simplify how binary is represented",
    "integrated development environment": "a software tool to help you write software",
    "integer": "a whole number, that is, with no fractional part, which can be positive, negative, or zero",
    "interface": "formal way in which two things interact",
    "internet": "a network of computers, routers, and other networks interconnected with a specific network communications protocol (TCP/IP)",
    "interpreter": "a  combination of a compiler and runtime environment that translates and executes a program in one step",
    "internet of things": "physical objects with embedded computers that represent the object on the internet",
    "information technology": "refers to general hardware, OS, and network design and support",
    "keyword": "a reserved word in the language that has special meaning in the language and cannot be appropriated for other purposes",
    "linux": "an operating system authored by Linus Torvalds as a free operating system",
    "local variable": "a variable that is accessible only in a portion of the code",
    "logic error": "a mistake in a program's source code that results in incorrect or unexpected behavior",
    "loop": "a control structure in the code that causes repeated execution of a section of code",
    "macintosh ": "a line of desktop and laptop computers developed by Apple",
    "machine learning": "a branch of Artificial Intelligence that uses statistical modeling to learn from experience",
    "malware": "software that is stealthly installed on a computer to damage, compromise, or acquire data",
    "memory": "addressable storage for storage and retrieval of bytes of data",
    "message passing": "a way to pass information between processes, machines, or threads that are running in parallel",
    "motherboard": "the main circuit board generally connecting most major components of a computer such as CPU, memory, I/O devices",
    "multi-core processor": "a chip with multiple processors and cache memory to speed execution",
    "nesting": "where information is organized in layers, or where objects contain other similar objects",
    "network": "an interconnected set of computers that can share information",
    "northbridge": "connects the CPU to high speed data components such as memory and graphics cards",
    "object-oriented programming": "a programming style in which variables and functions are associated in an object and visibility of the contents of the object is constrained",
    "object": "a collection of variables and functions brought together in a programming system to represent a physical thing, its data and its function",
    "open source": "an application or software which is provided with the source code, usually with few restrictions, for repurposing or augmenting",
    "operating system": "the program that runs on the computer hardware creating information objects such as files and processes and assures the fair and secure allocation of processor time, access to files, access to devices, and other resources",
    "operator": "a computational or mathematical operator such as ==, equal, *, +, /. It generally is used in-between the values to be used as input for the operator (called operands). For example 1+2",
    "personal computer": "stands for a Personal Computer running the Windows operating system and usually referred to as PC",
    "packet": "a unit of information into which data is broken up for transmission in a network or by other means",
    "pair programming": "a programming methodology that has two programmers set down at a single keyboard and display to program as a team effort, producing more and better working code",
    "parallel computing": "the field of Computer Science that deals with algorithms, techniques and hardware that enables simultaneous execution of many streams of instructions",
    "parallel": "executing at the same time on different CPUs or cores",
    "peripheral": "physical device used by a computer that is not part of the physical box containing CPU and memory",
    "port": "a physical socket on a computer for attaching the computer to external devices such as a printer or a router",
    "procedure": "a standalone segment of code with a clear set of inputs and output that performs a specific function",
    "process": "an operating system construct that is a running program",
    "programming": "the art of instructing computers how to store, retrieve, and process data automatically",
    "program": "an implementation of an algorithm",
    "proprietary": "owned by an individual or company and whose use generally requires payment",
    "protocol": "a standard for communication between pieces of hardware or between pieces of software that allows information and/or commands to be exchanged",
    "random access memory": "a form of computer memory that can be read and changed in any order, typically used to store working data and machine code, usually shortened to RAM",
    "ransomware": "malicious software designed to hold data hostage for money often by encrypting it",
    "reboot": "to restart a computer as if the computer had been powered down even though it was turned on and possibly running",
    "recursion": "the programming or algorithm technique of invoking a procedure from within itself",
    "router": "a networking device that forwards data packets between computer networks and may also be used to connect computers to a network",
    "shell": "a character based program that gives the user simple and programmatic access to the operating system via commands",
    "scalable computing": "an application supported on an amount of hardware that automatically adjusts to the size of the demand thereby saving money by using less hardware when demand is light and more when the demand is heavy",
    "scratch": "a language created by MIT containing colorful characters and easy for beginners to write programs without syntax errors",
    "semantic error": "a programming error that arises from a misunderstanding of the meaning or effect of some construct in a programming language",
    "server": "a computer that provides some service and is accessible over the internet",
    "simulation": "modeling the behaviors and conditions of the real world",
    "software": "a set of information that includes at least one program and optionally many programs and data files",
    "solid state disk": "uses chips to emulate a rotating disk but with no moving parts, usually shortened to SSD",
    "southbridge": "connects the CPU to lower speed data components such as internet, keyboard, audio, USB, etc",
    "statement": "a basic statement or command in program or the basic unit of a grammar of a programming language",
    "string": "an ordered sequence such as a set of bits or characters",
    "strongly-typed": "each type of data (such as integer, character, boolean) is predefined as part of the programming language and all constants or variables defined for a given program must be described with one of the data type",
    "syntax error": "error in the syntax of a sequence of characters or tokens that is intended to be written in a particular programming language",
    "telepresence": "a set of technologies which allows a person to feel as if they were present, to give the appearance of being present, and/or to have an effect as if present",
    "thread": "a thread is a “lightweight” subunit of execution of a process that can run in parallel with other threads in the process. It is a way to have parts of a process run simultaneously",
    "time sharing": "fairly splitting up time between running processes",
    "tractable": "solvable in a practical amount of time",
    "type": "kind of data that can be stored or referred to and has a specific set of operations that apply to it such as addition is an operation that is used on integers",
    "uniform resource locator": "a reference to a web resource that specifies its location on a computer network and a mechanism for retrieving it such as HTTP or FTP. It is shortened to URL.",
    "universal serial bus": "a popular standard for creating a data path between computers and peripherals",
    "unicode": "a method for encoding a string of symbols as bits",
    "variable": "a place in a running program where data is stored",
    "virtual machine": "a software implementation of a machine that executes programs like a physical machine",
    "windows": " proprietary operating system distributed by Microsoft",
}
